# This file allows packrat (used by rsconnect during deployment) to pick up dependencies.
library(bsicons)
library(bslib)
library(dplyr)
library(gargoyle)
library(quanteda)
library(quanteda.corpora)
library(quanteda.textplots)
library(quanteda.textstats)
library(readtext)
library(recommenderlab)
library(rhino)
library(shiny)
library(shiny.react)
library(shinyWidgets)
library(spacyr)
library(waiter)
